services:
  database:
    image: 'mysql:8.0'
    container_name: ${APP_NAME}-database
    restart: unless-stopped
    command: --default_authentication_plugin=mysql_native_password
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - livewire-network
    deploy:
      resources:
        limits:
          memory: 2048M
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  redis:
    image: 'redis:alpine'
    container_name: ${APP_NAME}-redis-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-volume:/data
    networks:
      - livewire-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - APP_ENV=${APP_ENV}
        - APP_PORT=${APP_PORT}
    volumes:
      - ./:/var/www/html
    ports:
      - ${APP_PORT}:8000
      - 5173:5173
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV}
      - ROOT=/var/www/html
    networks:
      - livewire-network
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
volumes:
  database-volume:
  redis-volume:
networks:
  livewire-network:
    driver: bridge
