services:
  database:
    image: 'mysql:8.0'
    container_name: ${APP_NAME}-database
    restart: unless-stopped
    command: --default_authentication_plugin=mysql_native_password
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - livewire-network
    deploy:
      resources:
        limits:
          memory: 2048M
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  redis:
    image: 'redis:alpine'
    container_name: ${APP_NAME}-redis-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-volume:/data
    networks:
      - livewire-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - APP_ENV=${APP_ENV}
        - APP_PORT=${APP_PORT}
    volumes:
      - ./:/var/www/html
    ports:
      - ${APP_PORT}:8000
      - 5173:5173
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV}
      - ROOT=/var/www/html
    networks:
      - livewire-network
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_healthy
      qdrant:
        condition: service_healthy
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: [ "sh", "-c" ]
    command: >
      "ollama serve & sleep 3 && ollama pull qwen3:0.6b && ollama pull nomic-embed-text && wait"
    networks:
      - livewire-network
    healthcheck:
      test: [ "CMD", "sh", "-c", "ollama ls | grep -q 'qwen3:0.6b' && ollama ls | grep -q 'nomic-embed-text'" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  qdrant:
    image: qdrant/qdrant
    container_name: ${APP_NAME}-qdrant
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - livewire-network
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
volumes:
  database-volume:
  redis-volume:
  ollama_data:
  qdrant_data:
networks:
  livewire-network:
    driver: bridge
